export const GOOGLE_TAG_ID = 'AW-1005517184';
export const GOOGLE_ANALYTICS_ID = 'G-B8HNPLWH5F';

export const GOOGLE_PAGE_VIEW_DESTINATIONS = `${GOOGLE_TAG_ID},${GOOGLE_ANALYTICS_ID}`;
export const GOOGLE_ADS_LEAD_CONVERSION = `${GOOGLE_TAG_ID}/afMlCKqXkeIbEIDzu98D`;
